### ISSUE TITLE
I can't run shell

### ISSUE THREAD

**Issue by fuorissimo** [nagadit/DeepFaceLab_Linux#10]
Hello, i have installed Linux Version on Google cloud.
But when i run, all sh give this error:

![Screenshot (370)](https://user-images.githubusercontent.com/35644089/94301209-78693b00-ff6a-11ea-929d-0dad7ba5366e.png)

Consider that directory there is it. I have try to change ev.sh file, using absolute path, but i don't resolve problem.

Directory was installed here:

/home/deepfaker/Deepfacelab_linux/...

**Comment by nagadit** [comment]
I don't understand what this problem is about, but try using a different shell like:

**Comment by fuorissimo** [comment]
Zoom image

**Comment by fuorissimo** [comment]
![Screenshot (371)](https://user-images.githubusercontent.com/35644089/94352256-e6912900-0062-11eb-970a-b6b703376b01.png)

There are no files, the path appears to be wrong. But actually there are

**Comment by fuorissimo** [comment]
Here you can see the path of scripts dir and workspace directory. As you can see, are correct. But when i start shell, i see error like file are not find. 

![Screenshot (372)](https://user-images.githubusercontent.com/35644089/94352333-e34a6d00-0063-11eb-8755-67db70455233.png)

**Comment by nagadit** [comment]
Try change all export [here](https://github.com/nagadit/DeepFaceLab_Linux/blob/1e462d454e8c06ddee973da35ec4b4318776add8/scripts/env.sh#L4) to SET

**Comment by fuorissimo** [comment]
No change....
![Uploading Screenshot (373).png…]()

**Comment by nagadit** [comment]
Change in this file all export commands to SET commands

**Comment by nagadit** [comment]
@fuorissimo working ?

**Comment by fuorissimo** [comment]
Dont work. I have also set in env.sh the absolute path.

![Screenshot (376)](https://user-images.githubusercontent.com/35644089/94352972-2dcfe780-006c-11eb-8390-33fd083daaeb.png)
![Screenshot (375)](https://user-images.githubusercontent.com/35644089/94352973-2f011480-006c-11eb-83ef-38fea2494e88.png)
![Screenshot (374)](https://user-images.githubusercontent.com/35644089/94352975-2f99ab00-006c-11eb-9924-5131eecbd5da.png)

**Comment by fuorissimo** [comment]
This is my last try, but dont work... Damn
![Screenshot (378)](https://user-images.githubusercontent.com/35644089/94353284-a5534600-006f-11eb-9665-357bc97ae029.png)

**Comment by fuorissimo** [comment]
I can give you user/psw?

**Comment by nagadit** [comment]
Run this `uname -a` and show me what you get

**Comment by fuorissimo** [comment]
![Screenshot (379)](https://user-images.githubusercontent.com/35644089/94392724-5c77bc00-0159-11eb-8ef7-cd8dba55da68.png)

**Comment by AhmedaliElgabry** [comment]
I have the same error ,did you find a solution for it ? thanks

**Comment by AhmedaliElgabry** [comment]
@nagadit 
@fuorissimo 
I have tried a lot to solve it with no results, so please if you find a solution guide me to it
Thanks

**Comment by fuorissimo** [comment]
I gave up: I rented a Windows-based GPU Cloud

**Comment by liufan777** [comment]
oh,I had the same error

**Comment by nagadit** [comment]
I am closing this issue, but feel free to reopen it if you feel like it or if you find a solution
