### ISSUE TITLE
Running a shell script in KDE Neon 20.04 gives error (Anaconda)

### ISSUE THREAD

**Issue by MrWitherSkull** [nagadit/DeepFaceLab_Linux#14]
The error given is. 

CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.

Running every single listed conda init commands give similar output.

(deepfacelab) inspirer@ArvidsPCKDE:~/DeepFaceLab_Linux/scripts$ conda init powershell
no change     /home/inspirer/anaconda3/condabin/conda
no change     /home/inspirer/anaconda3/bin/conda
no change     /home/inspirer/anaconda3/bin/conda-env
no change     /home/inspirer/anaconda3/bin/activate
no change     /home/inspirer/anaconda3/bin/deactivate
no change     /home/inspirer/anaconda3/etc/profile.d/conda.sh
no change     /home/inspirer/anaconda3/etc/fish/conf.d/conda.fish
no change     /home/inspirer/anaconda3/shell/condabin/Conda.psm1
no change     /home/inspirer/anaconda3/shell/condabin/conda-hook.ps1
no change     /home/inspirer/anaconda3/lib/python3.8/site-packages/xontrib/conda.xsh
no change     /home/inspirer/anaconda3/etc/profile.d/conda.csh
No action taken.
(deepfacelab) inspirer@ArvidsPCKDE:~/DeepFaceLab_Linux/scripts$ 

Help is appreciated.

Regards
Arvid Boisen

**Comment by danielhama** [comment]
You just need to run 
$"conda init bash" (if you are using bash)
then close and reopen the shell

**Comment by nagadit** [comment]
@danielhama is right

**Comment by nagadit** [comment]
I am closing this issue, but feel free to reopen it if you feel like it has not been resolved
