### ISSUE TITLE
Something is missing here

### ISSUE THREAD

**Issue by robustini** [nagadit/DeepFaceLab_Linux#24]
When I launch a train script it gives me this error:

Initializing models:   0%|                                | 0/5 [00:00<?, ?it/s]
Error: No OpKernel was registered to support Op 'DepthToSpace' used by node DepthToSpace (defined at home/marco/DeepFaceLab_Linux/DeepFaceLab/core/leras/ops/__init__.py:336)  with these attrs: [data_format="NCHW", block_size=2, T=DT_FLOAT]
Registered devices: [CPU]
Registered kernels:
  device='GPU'; T in [DT_QINT8]
  device='GPU'; T in [DT_HALF]
  device='GPU'; T in [DT_FLOAT]
  device='CPU'; T in [DT_VARIANT]; data_format in ["NHWC"]
  device='CPU'; T in [DT_RESOURCE]; data_format in ["NHWC"]

**Comment by wangmayset** [comment]
yes,me too.

**Comment by TheFeelTrain** [comment]
Same here. On an RTX 3070.

**Comment by robustini** [comment]
@nagadit why do you close the issue when the problem persists? :-)

**Comment by robustini** [comment]
> Same here. On an RTX 3070.

Yeah, me too on RTX 3070.
With Deepfacelab 2 for Windows no problems.

**Comment by robustini** [comment]
For RTX30 you need a special version of Tensorflow, follo the instructions here:

https://www.pugetsystems.com/labs/hpc/How-To-Install-TensorFlow-1-15-for-NVIDIA-RTX30-GPUs-without-docker-or-CUDA-install-2005/

**Comment by robustini** [comment]
![deepfacelab_linux](https://user-images.githubusercontent.com/3864712/103439546-1f323700-4c3e-11eb-9f17-2e035b6c232e.png)

**Comment by robustini** [comment]
![immagine](https://user-images.githubusercontent.com/3864712/103439697-784e9a80-4c3f-11eb-966a-cda727fff4f7.png)
