### ISSUE TITLE
Maybe this helps someone having issues

### ISSUE THREAD

**Issue by samsungderdull** [nagadit/DeepFaceLab_Linux#25]
First of all, thanks for maintaining this repo.

I had some struggle getting this running (again), first of all current env.sh defines "export DFL_PYTHON="python3.6"" but #3 of the installation instructions states "3.7". Changing env.sh to 3.7 worked.

I further had dependency-issues executing "conda create -n deepfacelab -c main python=3.7 cudnn=8.0.5 cudatoolkit=11.2" under Ubuntu 20.04, creating environment deepfacelab with anaconda-navigator & installing cudnn (7.6.5) & cudatoolkit (10.2.89) worked.

In my case, i also had to add "eval "$(conda shell.bash hook)"" to env.sh for not getting "CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'." error.

Hope this helps.

**Comment by robustini** [comment]
Same here, it is a known problem that has not yet been resolved.

**Comment by robustini** [comment]
And there's another error in the "equirements-cuda.txt":

The conflict is caused by:
    The user requested h5py==2.9.0
    tensorflow-gpu 2.4.0 depends on h5py~=2.10.0
