### ISSUE TITLE
Can not start a new thread with python3.6

### ISSUE THREAD

**Issue by yueanga** [nagadit/DeepFaceLab_Linux#33]
when i run bash 6_train_Quick96.sh

**Comment by nagadit** [comment]
required 3.7

**Comment by yueanga** [comment]
I've tried 3.7 before but a problem presented
> ImportError:/lib64/libm.so.6: version 'GLIBC_2.23' not found
and without the root authority I can not install "GLIBC_2.23" on lab server, I have to change python3.7 to 3.6
so could you help me with the problem about 'GLIBC_2.23' ?
thank you anyway

**Comment by yueanga** [comment]
> 
> 
> required 3.7
I've tried 3.7 before but a problem presented

    ImportError:/lib64/libm.so.6: version 'GLIBC_2.23' not found
    and without the root authority I can not install "GLIBC_2.23" on lab server, I have to change python3.7 to 3.6
    so could you help me with the problem about 'GLIBC_2.23' ?
    thank you anyway
