### ISSUE TITLE
/!\ ffmpeg fail problem

### ISSUE THREAD

**Issue by chlwnsgh5050** [nagadit/DeepFaceLab_Linux#36]
i am trying to launch bash 2_extract_image_from_data_src.sh

/!\ ffmpeg fail, job commandline:['ffmpeg', '-i', '/home/piai/DeepFaceLab_Linux/workspace/data_src.mp4', '-pix_fmt', 'rgb24', '/home/piai/DeepFaceLab_Linux/workspace/data_src/%5d.png']
Done.

but this happen... help please

**Comment by ogladkov** [comment]
reinstall ffmpeg with 'conda install -c conda-forge ffmpeg'

**Comment by chlwnsgh5050** [comment]
> conda install -c conda-forge ffmpeg

thank you~ i solved it
