### ISSUE TITLE
Инструкция по установке устарела.

### ISSUE THREAD

**Issue by Pheidologeton** [nagadit/DeepFaceLab_Linux#43]
Если всё делать по инструкции, deepfacelab не будет работать. Судя по всему, последняя версия deepfacelab не работает с CUDA версии ниже 11 и cudnn версии ниже 8. Так же requirements-cuda не подходят, с ними не появляется список видеокарт и обработка работает только на CPU. Мне помогла установка последних версий этих пакетов. 
Правильное создание окружения deepfacelab- conda create -n deepfacelab -c main python=3.7 cudnn=8.2.1 cudatoolkit=11
Установка нужных пакетов(переключившись на окружение deepfacelab)-  python -m pip install tqdm numpy h5py opencv-python ffmpeg-python scikit-image scipy colorama tensorflow-gpu pyqt5 tf2onnx
Надеюсь, что это вам поможет.

**Comment by nagadit** [comment]
Thank you for your feedback! by the end of the month new scripts from the original repo will be added and the instruction updated.
