### ISSUE TITLE
I tried to run the script after I finished the installation, but nothing returned

### ISSUE THREAD

**Issue by wayne0926** [nagadit/DeepFaceLab_Linux#44]
```
(deepfacelab)  wei@wei-B75  ~/文档/LAB/DeepFaceLab_Linux/scripts   master ±  ./2_extract_image_from_data_src.sh 


```
![2021-08-24 12-49-46屏幕截图](https://user-images.githubusercontent.com/63389859/130557509-89d23df6-cc71-4ecb-a93b-3148f7fb8e80.png)

just like this.
After running for an hour...two hours, there was still nothing. Is it a problem with the graphics card driver?

![2021-08-24 12-53-03屏幕截图](https://user-images.githubusercontent.com/63389859/130557744-c7a4d313-72e7-4437-a5d8-1621fb723c48.png)

![2021-08-24 12-54-16屏幕截图](https://user-images.githubusercontent.com/63389859/130557829-b36da74a-5dd5-4337-9dd7-50567dd6ff5c.png)

**Comment by wayne0926** [comment]
https://github.com/nagadit/DeepFaceLab_Linux/issues/43
 this
damn it

**Comment by sh3ll4rpw** [comment]
I have the same problem. This issue still remains @nagadit?
![Screenshot from 2022-12-05 21-54-03](https://user-images.githubusercontent.com/113100850/205753067-ecc431ab-263c-42cf-9933-1ed62470f806.png)

**Comment by stablummax** [comment]
I still have the same issue, is there any solution?

**Comment by wayne0926** [comment]
> I still have the same issue, is there any solution?

maybe you can try this way
https://github.com/nagadit/DeepFaceLab_Linux/issues/43#issue-959496591
