### ISSUE TITLE
Nvidia GPU is not detected / doesn't show option to choose GPU

### ISSUE THREAD

**Issue by th3j0ker** [nagadit/DeepFaceLab_Linux#52]
Hello,

I have been facing this issue since days now, finally had to ask it here.

So I have been using DFL on windows since quite some time now, it works smooth and in terms of installation and maintenance its a boon. but when it comes to performance I noticed that windows operating system was eating up almost 40% of my GPU memory due to some internal processes and it overall reduced my speed and accuracy. Hence I decided to switch to Linux version which I had used about two years ago and it gave amazing performance back then too.

Now the problem,

In windows, dfl used to give option to choose from either CPU ot Nvidia GPU for faceset extraction, merging and training, but when I run the same bash files on Linux it skips the part where I am supposed to choose either of those and as I can see that only 8 cores are printed when the extraction starts it is obvious that CPU is being used and not GPU.

Some Info on my system,
Kernel => Linux 192.168.1.5 5.14.18-300.fc35.x86_64 #1 SMP Fri Nov 12 16:43:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
CPU => AMD Ryzen 9 5900HX with Radeon Graphics
GPU => Nvidia RTX-3060 Mobile GPU
OS- Fedora 35

So here is what happens when i run command bash -i 5_data_dst_extract_faces_S3FD.sh, there used to be an option to choose for CPU or GPU in windows

===============================================================================
(deepfacelab) [mactimus@192 scripts]$ bash -i 5_data_dst_extract_faces_S3FD.sh
[wf] Face type ( f/wf/head ?:help ) : 
wf
[512] Image size ( 256-2048 ?:help ) : 
512
[90] Jpeg quality ( 1-100 ?:help ) : 
90
Extracting faces...

Running on CPU2
Running on CPU6
Running on CPU3
Running on CPU0
Running on CPU4
Running on CPU7
Running on CPU1
Running on CPU5

===============================================================================

I am able to see my device when i run,
------------------------------------------------------

**conda install numba
numba -s**

==================================================================================

Also when I run the following command in python env
-----------------------------------------------------------------------

**from tensorflow.python.client import device_lib
print(device_lib.list_local_devices())**

-------------------------I see the following ------------------

(deepfacelab) [mactimus@192 scripts]$ python
Python 3.7.11 (default, Jul 27 2021, 14:32:16) 
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from tensorflow.python.client import device_lib
2021-11-24 12:57:07.902835: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
>>> print(device_lib.list_local_devices())
2021-11-24 12:57:13.142488: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-11-24 12:57:13.143137: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcuda.so.1
2021-11-24 12:57:14.272368: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-11-24 12:57:14.272548: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: NVIDIA GeForce RTX 3060 Laptop GPU computeCapability: 8.6
coreClock: 1.702GHz coreCount: 30 deviceMemorySize: 5.81GiB deviceMemoryBandwidth: 312.97GiB/s
2021-11-24 12:57:14.272581: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2021-11-24 12:57:14.274654: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.11
2021-11-24 12:57:14.274722: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublasLt.so.11
2021-11-24 12:57:14.289957: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcufft.so.10
2021-11-24 12:57:14.290264: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcurand.so.10
2021-11-24 12:57:14.290364: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcusolver.so.10'; dlerror: libcusolver.so.10: cannot open shared object file: No such file or directory
2021-11-24 12:57:14.291851: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusparse.so.11
2021-11-24 12:57:14.292030: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudnn.so.8'; dlerror: libcudnn.so.8: cannot open shared object file: No such file or directory
2021-11-24 12:57:14.292052: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1757] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2021-11-24 12:57:14.330203: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1261] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-11-24 12:57:14.330238: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1267]      0 
2021-11-24 12:57:14.330244: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1280] 0:   N 
[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 7823247586605606195
]

====================================================================================

Here is my output for command nvidia-smi
---------------------------------------------------------

**(base) [mactimus@192 ~]$ nvidia-smi** 
Wed Nov 24 12:54:56 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 495.44       Driver Version: 495.44       CUDA Version: 11.5     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   43C    P0    N/A /  N/A |      5MiB /  5946MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1901      G   /usr/libexec/Xorg                   4MiB |
+-----------------------------------------------------------------------------+

Any help is most welcomed,
Thanks

**Comment by th3j0ker** [comment]
### Installing DLF on Linux for Noobs (like me)

Firstly thanks @nagadit for maintaining this repo, It helps a lot! 

After a few days of research I was finally able to run DFL on linux with RTX3060 mobile GPU, anyone who is struggling with the same issue as I can follow these steps, 

_CPU => AMD Ryzen 9 5900HX with Radeon Graphics
GPU => Nvidia RTX-3060 Mobile GPU
OS => Ubuntu 21.10
Kernel=> 5.13.0-21-generic #21-Ubuntu SMP Tue Oct 19 08:59:28 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux_

I tested multiple linux distros (Fedora,Manjaro,Garuda,mint etc) and the one that was working perfectly with minimum hassle for installation was ubuntu, I used 21.10 because 20.04(LTS) was missing drivers for my mediatek network card you can use that too if you wish.

I realised that the cudatoolkit and cudnn that i was trying to install via anaconda (apart from being outdated) was not able to detect my GPU, so I decided to install all directly to system, instead of using conda install cudatoolkit.

**Step 1.)** install proprietary **nvidia drivers** from repository, 

for some reason the latest driver for my RTX was not working properly hence I installed a stable one by typing in shell,

`sudo apt install nvidia-driver-470`

once installed, reboot.

type in shell `nvidia-smi `to verify installation

**Step 2.)** install **cudatoolkit** from repository,

**_**Important: If you install a cudatoolkit version that is not compatible with your driver it will automatically uninstall your currently installed nvidia driver._**

check for version compatibility at https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html

`sudo apt install nvidia-cuda-toolkit`

this for me installed 11.3 cuda which is indeed compatible with nvidia 470 driver,

once this is installed, reboot.

type in shell `nvcc --version` to verify installation

**Step 3.)** install **cudnn** from nvidia official website,

for nvidia cudnn download, you will have to sign up for nvidia developers account and proceed with installation.

url: https://developer.nvidia.com/cudnn

be careful, cudnn should be compatible with the cuda version that we installed in previous step, so in by case the cudnn should be compatible with 11.3, which was 8.2.1. 

choose a version that is compatible with your cuda version and download all three files .deb, i.e. 

libcudnn8_8.2.1.32-1+cuda11.3_amd64.deb
libcudnn8-dev_8.2.1.32-1+cuda11.3_amd64.deb
libcudnn8-samples_8.2.1.32-1+cuda11.3_amd64.deb

install these with dpkg and reboot.

**Step 4.)** install **anaconda**

goto: https://www.anaconda.com/products/individual 

download and install

**Step 5.)** setup **conda** environment

move to directory of your choice and type in shell,

`conda create -n deepfacelab -c main python=3.9`
` conda activate deepfacelab`

_Note: removed cudnn and cudatoolkit as they are no longer required to be installed with conda_

**Step 6.)** Initialize **Deepfacelab** environment

```
 git clone --depth 1 https://github.com/nagadit/DeepFaceLab_Linux.git
 cd DeepFaceLab_Linux
 git clone --depth 1 https://github.com/iperov/DeepFaceLab.git
```

**Step 7.)** install python requirements

Open requirements-cuda.txt file by typing,

`nano DeepFaceLab/requirements-cuda.txt`

and change the requirements file to,

```
tensorflow-gpu==2.5.0
tqdm
numpy
numexpr
h5py
opencv-python
ffmpeg-python
scikit-image
scipy
colorama
pyqt5
tf2onnx

```
save and proceed to installation by typing in shell

`python -m pip install -r ./DeepFaceLab/requirements-cuda.txt`

**Finally!!**

Step 8.) changing **env.sh** file in scripts,

goto scripts by typing in shell,

`cd scripts/`

open env.sh,

`nano env.sh`

edit the following line,

`export DFL_PYTHON="python3.7" `

and replace 3.7 with 3.9,

`export DFL_PYTHON="python3.9"`

save and exit

**Step 10.)** Enjoy!!!!!

**Comment by billfang235** [comment]
As a reminder for myself and a note for people wondering the `opencv-python==4.1.2.30` in requirements-cuda.txt, if pip could not find `opencv-python==4.1.2.30`, `opencv-python-headless` is a feasible alternative (tested in wslg).
`opencv-python` may induce load error in wlsg.[https://github.com/NVlabs/instant-ngp/discussions/300](url)

If Xseg editor cannot open display in wslg, check here [https://github.com/microsoft/wslg/issues/558#issuecomment-1260817709](url).

**Comment by smaiht** [comment]
I dont know, it's not working at all...

**Comment by laurentbenaroya** [comment]
I have the same problem. I tried the proposed solution, but it doesn't solve the problem. In 5_Xseg_train.sh, the CPU is automatically selected.
