### ISSUE TITLE
Please update the Readme

### ISSUE THREAD

**Issue by 1840742330** [nagadit/DeepFaceLab_Linux#6]
install the deepfacelab as the README.md  
iit will have erro like :::::
[[[[[[
python3.6: can't open file './deepfacelab/main.py':
]]]]]]
if you cut the folder 'DeepFaceLab' to the folder 'scripts' can solve this promblem (just place the folders as the windows version)

then 
another issue came out  
run the .sh
[[[
Traceback (most recent call last):
。。。
import error LibXrender 
]]]
after install 
libsm6  
libxrender1
libxext-dev

**Comment by nagadit** [comment]
done )
