### ISSUE TITLE
only use cpu train SAEHD

### ISSUE THREAD

**Issue by xiao-song2022** [nagadit/DeepFaceLab_Linux#66]
![image](https://user-images.githubusercontent.com/109330558/190642088-6252eaf6-8452-44a6-8c40-7516b73d26f3.png)
Since it is in a Cloud Servers, parameters cannot be passed in. All parameters are default values
and anaconda = 2021.05 cuda=11.3.
appreciate!

**Comment by VladPedro** [comment]
use TF 2.10

**Comment by xiao-song2022** [comment]
i solve this by load following
conda
cuda/11.3
gcc/8.3
cudnn/8.2.1_cuda11.x

**Comment by smaiht** [comment]
> i solve this by load following conda cuda/11.3 gcc/8.3 cudnn/8.2.1_cuda11.x

What do you mean "by load following conda cuda/11.3 gcc/8.3 cudnn/8.2.1_cuda11.x" ?
How do I do that?
