### ISSUE TITLE
Can you please post a license?

### ISSUE THREAD

**Issue by lgritz** [nagadit/DeepFaceLab_Linux#73]
With no license explicitly posted, legally speaking a project defaults to nobody having permission to use these in any way, which causes many companies to just forbid any use whatsoever.

Can you please choose an appropriate common open source license and add it to the repository? Thanks.

**Comment by nagadit** [comment]
Because this repository is a fork of the original, then the license is the same

**Comment by lgritz** [comment]
So sorry, I didn't even notice that it was a fork. Thanks for the info.
